version: '3.8'
services:
  nginx:
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - ./build:/usr/share/nginx/html
      - ./default.config:/etc/nginx/conf.d/default.conf
      #docker compose -p evosolution-frontend up -d
